SRC=	Client.java \
	MainWindow.java \
	Test.java
OBJ=	Client.class \
	MainWindow.class \
	Test.class
NAME=	Client

all:
	javac $(SRC)

$(NAME): all

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: fclean all 
